%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 746.83421481 #741.312638297844
Camera.fy: 750.92814502 #741.073423195241
Camera.cx: 271.31554363 #253.312815803906
Camera.cy: 117.01321308 #198.380096440710

Camera.k1: -0.3926455   #-0.356142649377706
Camera.k2: 1.74617425   #1.70379730862432
Camera.p1: -0.00800657  #-0.000782405617012491
Camera.p2: 0.00549376   #-0.00120515059343290
Camera.k3: -5.48740347  #-3.73668434801387

# Camera frames per second 
Camera.fps: 30.0 #30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1 #1

Camera.width: 568
Camera.height: 400

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000 #1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2 #1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8 #8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20 #20
ORBextractor.minThFAST: 7 #7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05 #0.05
Viewer.KeyFrameLineWidth: 1 #1
Viewer.GraphLineWidth: 0.9 #0.9
Viewer.PointSize: 2 #2
Viewer.CameraSize: 0.08 #0.08
Viewer.CameraLineWidth: 3 #3
Viewer.ViewpointX: 0 #0
Viewer.ViewpointY: -0.7 #-0.7
Viewer.ViewpointZ: -1.8 #-1.8
Viewer.ViewpointF: 500 #500